imx93_nitrogen_smarc: initial addition
imx93_nitrogen_smarc: fix  undefined reference to mmc_map_to_kernel_blk
arm: dts: imx93-nitrogen-smarc: fix incorrect ethphy2 interrupt pin
imx93_nitrogen_smarc: use bl31-iMX93.bin instead of bl31.bin
imx93_nitrogen_smarc: enable FIT format

Signed-off-by: Simon Gaynor <simon.gaynor@lairdconnect.com>

imx93_nitrogen_smarc: rename folder
imx93_nitrogen_smarc: align with latest evk code
imx93_nitrogen_smarc: run savedefconfig
imx93_nitrogen_smarc: fix build issues
imx93_nitrogen_smarc: align dts with evk
arm: dts: imx93-nitrogen-smarc: fix ethernet phy resets
imx93_nitrogen_smarc_defconfig: fix USB IDs
imx93_nitrogen_smarc: add serial# variable
imx93_nitrogen_smarc: fix indentation
imx93_nitrogen_smarc: remove unnecessary bl31 binary
imx93_nitrogen_smarc: fix build issue
imx93_nitrogen_smarc: sync default env with other nitrogen platforms
imx93_nitrogen_smarc: fix indentation issues
imx93_nitrogen_smarc_defconfig: add ahab configuration

Signed-off-by: Gary Bisson <gary.bisson@ezurio.com>